[package]
name = "fits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tensor = {path = "../tensor"}
eyre = "0.6.8"
tightness = "1.0.1"
ndarray = "0.15.6"
image = "0.24.7"
viuer = "0.7.1"
